add_subdirectory(fx)
add_subdirectory(modulator)

add_library(module module.cpp)
target_link_libraries(module PRIVATE synthesizer utils)
add_library(mixer mixer.cpp)
target_link_libraries(mixer PRIVATE module utils)
add_library(master master.cpp)
target_link_libraries(master PRIVATE mixer module utils)
add_library(noise_generator noise_generator.cpp)
target_link_libraries(noise_generator PRIVATE module utils)
add_library(oscillator oscillator.cpp)
target_link_libraries(oscillator PRIVATE module midi utils)
add_library(performed_oscillator performed_oscillator.cpp)
target_link_libraries(performed_oscillator PRIVATE oscillator midi)
add_library(voice voice.cpp)
target_link_libraries(voice PRIVATE module oscillator midi)
add_library(voice_manager voice_manager.cpp)
target_link_libraries(voice_manager PRIVATE module voice synthesizer utils)
